AllCops:
  Exclude:
    - 'test_braminus.rb'

# Not particularly proud of it, but these are necessary for now...
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/MethodLength:
  Max: 35
Metrics/AbcSize:
  Max: 35
Metrics/BlockLength:
  Enabled: false
