AllCops:
  Exclude:
    - 'test_braminus.rb'

Style/ClassVars:
  Enabled: false

# Not particularly proud of it, but these are necessary for now...
Metrics/MethodLength:
  Max: 13
Metrics/AbcSize:
  Max: 18
